### ISSUE TITLE
Does introducing noise-only samples in training reduce hallucinations?

### ISSUE THREAD

**Issue by joelai0101** [nyrahealth/CrisperWhisper#3]
I would like to know if this approach is truly effective in mitigating hallucinations in the Whisper model.

**Comment by LaurinmyReha** [comment]
Yes it helps quite a bit but it does not mitigate all hallucinations completely as is. I am currently looking into different approaches how to make the trained cross attention heads effective for detecting hallucinations even more robustly. Since they were acutally trained i would expect these attention heads to behave somehow ,,weird" like having increased entropy in there cross attention distribution or things like that. As a simple heuristic that is very is to implement on top of the current model: if the duration of a sequence of words is very very short as given by the timestamps these words are likely hallucinated.

**Comment by LaurinmyReha** [comment]
Yes this is certainly possible :) 

You will have to be a careful tough and add a meaningful amount of additional data in the language(s) you are interested in to not degrade the performance of the base model. Happy tuning!

**Comment by LaurinmyReha** [comment]
> I randomly selected noise from noise data, added it to the original speech data, and used it to generate a noise-only sample. Is that OK?

Not quite, noise only samples contain no speech. Therefore adding noise with speech will not result in a noise only sample.

Please carefully study section three, especially 3.2 of the paper. The details are given there.
https://arxiv.org/pdf/2408.16589
