### ISSUE TITLE
Retokenization

### ISSUE THREAD

**Issue by kelseyjd** [nyrahealth/CrisperWhisper#8]
Hi, could you explain in a more practical manner how the retokenization is performed? 

`Therefore, we propose to simply strip all tokens in the vocabulary of spaces, except the space token itself, and keep only the unique tokens. We adjust the merges in the tokenizer to be congruent with this reduced vocabulary`

Looking at the vocab.json file in the original Whisper multilingual tokenizer, there are no spaces inside the tokens. How do you find and remove the spaces?

**Comment by LaurinmyReha** [comment]
Sure, if you checkout this file for the original whisper-v3:

https://huggingface.co/openai/whisper-large-v3/raw/main/vocab.json

you will see this token a lot:

`Ġ`

This token represents the space token in the vocabulary. Therefore we strip the vocabulary of this token and only let the original space token ( the one with id 220) remain. For all of the tokens that are duplicated after removing the space or equivalently the `Ġ` we take the one with the smaller index and eliminate the other. Because this is a BPE tokenizer one needs to adjust the mergetable accordingly. I hope this solves your problem otherwise let me know.
